/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ViewEvent_SPtr : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ViewEvent_SPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(ViewEvent_SPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ViewEvent_SPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        view_model_swigPINVOKE.delete_ViewEvent_SPtr(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public ViewEvent_SPtr() : this(view_model_swigPINVOKE.new_ViewEvent_SPtr__SWIG_0(), true) {
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public ViewEvent_SPtr(ViewEvent p, bool add_ref) : this(view_model_swigPINVOKE.new_ViewEvent_SPtr__SWIG_1(ViewEvent.getCPtr(p), add_ref), true) {
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public ViewEvent_SPtr(ViewEvent p) : this(view_model_swigPINVOKE.new_ViewEvent_SPtr__SWIG_2(ViewEvent.getCPtr(p)), true) {
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public ViewEvent_SPtr(ViewEvent_SPtr rhs) : this(view_model_swigPINVOKE.new_ViewEvent_SPtr__SWIG_3(ViewEvent_SPtr.getCPtr(rhs)), true) {
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    view_model_swigPINVOKE.ViewEvent_SPtr_reset__SWIG_0(swigCPtr);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset(ViewEvent rhs) {
    view_model_swigPINVOKE.ViewEvent_SPtr_reset__SWIG_1(swigCPtr, ViewEvent.getCPtr(rhs));
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public ViewEvent get() {
    IntPtr cPtr = view_model_swigPINVOKE.ViewEvent_SPtr_get(swigCPtr);
    ViewEvent ret = (cPtr == IntPtr.Zero) ? null : new ViewEvent(cPtr, false);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ViewEvent __ref__() {
    ViewEvent ret = new ViewEvent(view_model_swigPINVOKE.ViewEvent_SPtr___ref__(swigCPtr), false);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ViewEvent __deref__() {
    IntPtr cPtr = view_model_swigPINVOKE.ViewEvent_SPtr___deref__(swigCPtr);
    ViewEvent ret = (cPtr == IntPtr.Zero) ? null : new ViewEvent(cPtr, false);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void swap(ViewEvent_SPtr rhs) {
    view_model_swigPINVOKE.ViewEvent_SPtr_swap(swigCPtr, ViewEvent_SPtr.getCPtr(rhs));
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isNull() {
    bool ret = view_model_swigPINVOKE.ViewEvent_SPtr_isNull(swigCPtr);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isNotNull() {
    bool ret = view_model_swigPINVOKE.ViewEvent_SPtr_isNotNull(swigCPtr);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public ViewEvent_SPtr create(string strValue) {
    ViewEvent_SPtr ret = new ViewEvent_SPtr(view_model_swigPINVOKE.ViewEvent_SPtr_create(swigCPtr, view_model_swigPINVOKE.UnmanagedString.Create(strValue)), true);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getValue() {
  // Generated from %typemap(csout) string
  string ret = view_model_swigPINVOKE.UnmanagedString.Consume(view_model_swigPINVOKE.ViewEvent_SPtr_getValue(swigCPtr));
  
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public ViewEvent dynamic_cast(NotifierEvent pSource) {
    IntPtr cPtr = view_model_swigPINVOKE.ViewEvent_SPtr_dynamic_cast(swigCPtr, NotifierEvent.getCPtr(pSource));
    ViewEvent ret = (cPtr == IntPtr.Zero) ? null : new ViewEvent(cPtr, false);
    if (view_model_swigPINVOKE.SWIGPendingException.Pending) throw view_model_swigPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
