/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class IClassInfo : PYXCOM_IUnknown {
  private HandleRef swigCPtr;

  public IClassInfo(IntPtr cPtr, bool cMemoryOwn) : base(pyxlibPINVOKE.IClassInfoUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(IClassInfo obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IClassInfo() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pyxlibPINVOKE.delete_IClassInfo(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static GUID iid {
    get {
      IntPtr cPtr = pyxlibPINVOKE.IClassInfo_iid_get();
      GUID ret = (cPtr == IntPtr.Zero) ? null : new GUID(cPtr, false);
      if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public virtual int getClass(SWIGTYPE_p_p__GUID ppclsid) {
    int ret = pyxlibPINVOKE.IClassInfo_getClass(swigCPtr, SWIGTYPE_p_p__GUID.getCPtr(ppclsid));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int getNumInterfaces(SWIGTYPE_p_int pNumInterfaces) {
    int ret = pyxlibPINVOKE.IClassInfo_getNumInterfaces(swigCPtr, SWIGTYPE_p_int.getCPtr(pNumInterfaces));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual int getInterfaces(SWIGTYPE_p_p__GUID ppiid) {
    int ret = pyxlibPINVOKE.IClassInfo_getInterfaces(swigCPtr, SWIGTYPE_p_p__GUID.getCPtr(ppiid));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
