/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class ProcessVersionEvent : ProcessEvent {
  private HandleRef swigCPtr;

  public ProcessVersionEvent(IntPtr cPtr, bool cMemoryOwn) : base(pyxlibPINVOKE.ProcessVersionEventUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(ProcessVersionEvent obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ProcessVersionEvent() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pyxlibPINVOKE.delete_ProcessVersionEvent(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static SWIGTYPE_p_boost__intrusive_ptrTProcessVersionEvent_t create(IProcess_SPtr spProc) {
    SWIGTYPE_p_boost__intrusive_ptrTProcessVersionEvent_t ret = new SWIGTYPE_p_boost__intrusive_ptrTProcessVersionEvent_t(pyxlibPINVOKE.ProcessVersionEvent_create(IProcess_SPtr.getCPtr(spProc)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
