/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class IViewPoint : PYXCOM_IUnknown {
  private HandleRef swigCPtr;

  public IViewPoint(IntPtr cPtr, bool cMemoryOwn) : base(pyxlibPINVOKE.IViewPointUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(IViewPoint obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IViewPoint() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pyxlibPINVOKE.delete_IViewPoint(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static GUID iid {
    get {
      IntPtr cPtr = pyxlibPINVOKE.IViewPoint_iid_get();
      GUID ret = (cPtr == IntPtr.Zero) ? null : new GUID(cPtr, false);
      if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public virtual Vector_IProcess getCoveragePipelines() {
    Vector_IProcess ret = new Vector_IProcess(pyxlibPINVOKE.IViewPoint_getCoveragePipelines(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Vector_IProcess getFeatureCollectionPipelines() {
    Vector_IProcess ret = new Vector_IProcess(pyxlibPINVOKE.IViewPoint_getFeatureCollectionPipelines(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Vector_IProcess getElevationPipelines() {
    Vector_IProcess ret = new Vector_IProcess(pyxlibPINVOKE.IViewPoint_getElevationPipelines(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Vector_IProcess getAllPipelines() {
    Vector_IProcess ret = new Vector_IProcess(pyxlibPINVOKE.IViewPoint_getAllPipelines(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual Notifier getViewPointChangedNotifier() {
    Notifier ret = new Notifier(pyxlibPINVOKE.IViewPoint_getViewPointChangedNotifier(swigCPtr), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
