/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PYXCellHistogram_SPtr : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public PYXCellHistogram_SPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(PYXCellHistogram_SPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PYXCellHistogram_SPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pyxlibPINVOKE.delete_PYXCellHistogram_SPtr(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public PYXCellHistogram_SPtr() : this(pyxlibPINVOKE.new_PYXCellHistogram_SPtr__SWIG_0(), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXCellHistogram_SPtr(PYXCellHistogram p, bool add_ref) : this(pyxlibPINVOKE.new_PYXCellHistogram_SPtr__SWIG_1(PYXCellHistogram.getCPtr(p), add_ref), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXCellHistogram_SPtr(PYXCellHistogram p) : this(pyxlibPINVOKE.new_PYXCellHistogram_SPtr__SWIG_2(PYXCellHistogram.getCPtr(p)), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXCellHistogram_SPtr(PYXCellHistogram_SPtr rhs) : this(pyxlibPINVOKE.new_PYXCellHistogram_SPtr__SWIG_3(PYXCellHistogram_SPtr.getCPtr(rhs)), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    pyxlibPINVOKE.PYXCellHistogram_SPtr_reset__SWIG_0(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset(PYXCellHistogram rhs) {
    pyxlibPINVOKE.PYXCellHistogram_SPtr_reset__SWIG_1(swigCPtr, PYXCellHistogram.getCPtr(rhs));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXCellHistogram get() {
    IntPtr cPtr = pyxlibPINVOKE.PYXCellHistogram_SPtr_get(swigCPtr);
    PYXCellHistogram ret = (cPtr == IntPtr.Zero) ? null : new PYXCellHistogram(cPtr, false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXCellHistogram __ref__() {
    PYXCellHistogram ret = new PYXCellHistogram(pyxlibPINVOKE.PYXCellHistogram_SPtr___ref__(swigCPtr), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXCellHistogram __deref__() {
    IntPtr cPtr = pyxlibPINVOKE.PYXCellHistogram_SPtr___deref__(swigCPtr);
    PYXCellHistogram ret = (cPtr == IntPtr.Zero) ? null : new PYXCellHistogram(cPtr, false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void swap(PYXCellHistogram_SPtr rhs) {
    pyxlibPINVOKE.PYXCellHistogram_SPtr_swap(swigCPtr, PYXCellHistogram_SPtr.getCPtr(rhs));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isNull() {
    bool ret = pyxlibPINVOKE.PYXCellHistogram_SPtr_isNull(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isNotNull() {
    bool ret = pyxlibPINVOKE.PYXCellHistogram_SPtr_isNotNull(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getCellResolution() {
    int ret = pyxlibPINVOKE.PYXCellHistogram_SPtr_getCellResolution(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RangeDouble getArea() {
    RangeDouble ret = new RangeDouble(pyxlibPINVOKE.PYXCellHistogram_SPtr_getArea__SWIG_0(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RangeDouble getArea(RangePYXValue range) {
    RangeDouble ret = new RangeDouble(pyxlibPINVOKE.PYXCellHistogram_SPtr_getArea__SWIG_1(swigCPtr, RangePYXValue.getCPtr(range)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXCellHistogramBinVector getCellBins() {
    PYXCellHistogramBinVector ret = new PYXCellHistogramBinVector(pyxlibPINVOKE.PYXCellHistogram_SPtr_getCellBins(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXCellHistogramBinVector getCellNormalizedBins(PYXHistogram.Normalization mode, int binCount) {
    PYXCellHistogramBinVector ret = new PYXCellHistogramBinVector(pyxlibPINVOKE.PYXCellHistogram_SPtr_getCellNormalizedBins(swigCPtr, (int)mode, binCount), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXHistogram_SPtr createFromFeatures(FeatureIterator_SPtr features, int fieldIndex) {
    PYXHistogram_SPtr ret = new PYXHistogram_SPtr(pyxlibPINVOKE.PYXCellHistogram_SPtr_createFromFeatures(swigCPtr, FeatureIterator_SPtr.getCPtr(features), fieldIndex), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RangeInt getFeatureCount() {
    RangeInt ret = new RangeInt(pyxlibPINVOKE.PYXCellHistogram_SPtr_getFeatureCount__SWIG_0(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RangeInt getFeatureCount(RangePYXValue range) {
    RangeInt ret = new RangeInt(pyxlibPINVOKE.PYXCellHistogram_SPtr_getFeatureCount__SWIG_1(swigCPtr, RangePYXValue.getCPtr(range)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getSum() {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXCellHistogram_SPtr_getSum(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getAverage() {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXCellHistogram_SPtr_getAverage(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getSumSquare() {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXCellHistogram_SPtr_getSumSquare(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public RangePYXValue getBoundaries() {
    RangePYXValue ret = new RangePYXValue(pyxlibPINVOKE.PYXCellHistogram_SPtr_getBoundaries(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXHistogramBinVector getBins() {
    PYXHistogramBinVector ret = new PYXHistogramBinVector(pyxlibPINVOKE.PYXCellHistogram_SPtr_getBins(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXHistogramBinVector getNormalizedBins(PYXHistogram.Normalization mode, int binCount) {
    PYXHistogramBinVector ret = new PYXHistogramBinVector(pyxlibPINVOKE.PYXCellHistogram_SPtr_getNormalizedBins(swigCPtr, (int)mode, binCount), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void add(PYXValue value) {
    pyxlibPINVOKE.PYXCellHistogram_SPtr_add__SWIG_0(swigCPtr, PYXValue.getCPtr(value));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void add(PYXHistogram histogram) {
    pyxlibPINVOKE.PYXCellHistogram_SPtr_add__SWIG_1(swigCPtr, PYXHistogram.getCPtr(histogram));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

}
