/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PYXPrimeInnerTileIterator : PYXAbstractIterator {
  private HandleRef swigCPtr;

  public PYXPrimeInnerTileIterator(IntPtr cPtr, bool cMemoryOwn) : base(pyxlibPINVOKE.PYXPrimeInnerTileIteratorUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(PYXPrimeInnerTileIterator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PYXPrimeInnerTileIterator() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pyxlibPINVOKE.delete_PYXPrimeInnerTileIterator(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static void test() {
    pyxlibPINVOKE.PYXPrimeInnerTileIterator_test();
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXPrimeInnerTileIterator() : this(pyxlibPINVOKE.new_PYXPrimeInnerTileIterator(), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static PYXIcosIndex getPrimeInnerTileRoot(PYXIcosIndex index) {
    PYXIcosIndex ret = new PYXIcosIndex(pyxlibPINVOKE.PYXPrimeInnerTileIterator_getPrimeInnerTileRoot(PYXIcosIndex.getCPtr(index)), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static PYXIcosIndex getPrimeInnerTileRootByPosition(uint position) {
    PYXIcosIndex ret = new PYXIcosIndex(pyxlibPINVOKE.PYXPrimeInnerTileIterator_getPrimeInnerTileRootByPosition(position), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static uint getPrimeInnerTileRootPosition(PYXIcosIndex index) {
    uint ret = pyxlibPINVOKE.PYXPrimeInnerTileIterator_getPrimeInnerTileRootPosition(PYXIcosIndex.getCPtr(index));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static void initStaticData() {
    pyxlibPINVOKE.PYXPrimeInnerTileIterator_initStaticData();
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void freeStaticData() {
    pyxlibPINVOKE.PYXPrimeInnerTileIterator_freeStaticData();
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXIcosIndex getIndex() {
    PYXIcosIndex ret = new PYXIcosIndex(pyxlibPINVOKE.PYXPrimeInnerTileIterator_getIndex(swigCPtr), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint getPosition() {
    uint ret = pyxlibPINVOKE.PYXPrimeInnerTileIterator_getPosition(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void next() {
    pyxlibPINVOKE.PYXPrimeInnerTileIterator_next(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public override bool end() {
    bool ret = pyxlibPINVOKE.PYXPrimeInnerTileIterator_end(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly uint totalCount = pyxlibPINVOKE.PYXPrimeInnerTileIterator_totalCount_get();
}
