/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class PYXValueTile_SPtr : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public PYXValueTile_SPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(PYXValueTile_SPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~PYXValueTile_SPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        pyxlibPINVOKE.delete_PYXValueTile_SPtr(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public PYXValueTile_SPtr() : this(pyxlibPINVOKE.new_PYXValueTile_SPtr__SWIG_0(), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXValueTile_SPtr(PYXValueTile p, bool add_ref) : this(pyxlibPINVOKE.new_PYXValueTile_SPtr__SWIG_1(PYXValueTile.getCPtr(p), add_ref), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXValueTile_SPtr(PYXValueTile p) : this(pyxlibPINVOKE.new_PYXValueTile_SPtr__SWIG_2(PYXValueTile.getCPtr(p)), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXValueTile_SPtr(PYXValueTile_SPtr rhs) : this(pyxlibPINVOKE.new_PYXValueTile_SPtr__SWIG_3(PYXValueTile_SPtr.getCPtr(rhs)), true) {
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    pyxlibPINVOKE.PYXValueTile_SPtr_reset__SWIG_0(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset(PYXValueTile rhs) {
    pyxlibPINVOKE.PYXValueTile_SPtr_reset__SWIG_1(swigCPtr, PYXValueTile.getCPtr(rhs));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXValueTile get() {
    IntPtr cPtr = pyxlibPINVOKE.PYXValueTile_SPtr_get(swigCPtr);
    PYXValueTile ret = (cPtr == IntPtr.Zero) ? null : new PYXValueTile(cPtr, false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile __ref__() {
    PYXValueTile ret = new PYXValueTile(pyxlibPINVOKE.PYXValueTile_SPtr___ref__(swigCPtr), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile __deref__() {
    IntPtr cPtr = pyxlibPINVOKE.PYXValueTile_SPtr___deref__(swigCPtr);
    PYXValueTile ret = (cPtr == IntPtr.Zero) ? null : new PYXValueTile(cPtr, false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void swap(PYXValueTile_SPtr rhs) {
    pyxlibPINVOKE.PYXValueTile_SPtr_swap(swigCPtr, PYXValueTile_SPtr.getCPtr(rhs));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isNull() {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_isNull(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isNotNull() {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_isNotNull(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void test() {
    pyxlibPINVOKE.PYXValueTile_SPtr_test(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXValueTile_SPtr create(SWIGTYPE_p_std__istream arg0) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_create__SWIG_0(swigCPtr, SWIGTYPE_p_std__istream.getCPtr(arg0)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr create(PYXIcosIndex index, int nRes, PYXTableDefinition_CSPtr spDefn) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_create__SWIG_1(swigCPtr, PYXIcosIndex.getCPtr(index), nRes, PYXTableDefinition_CSPtr.getCPtr(spDefn)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr create(PYXValueTile source) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_create__SWIG_2(swigCPtr, PYXValueTile.getCPtr(source)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr create(PYXTile tile, PYXTableDefinition_CSPtr spDefn) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_create__SWIG_3(swigCPtr, PYXTile.getCPtr(tile), PYXTableDefinition_CSPtr.getCPtr(spDefn)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr create(PYXTile tile, SWIGTYPE_p_std__vectorTPYXValue__eType_t vecTypes) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_create__SWIG_4(swigCPtr, PYXTile.getCPtr(tile), SWIGTYPE_p_std__vectorTPYXValue__eType_t.getCPtr(vecTypes)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr create(PYXTile tile, SWIGTYPE_p_std__vectorTPYXValue__eType_t vecTypes, Vector_Int vecCounts) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_create__SWIG_5(swigCPtr, PYXTile.getCPtr(tile), SWIGTYPE_p_std__vectorTPYXValue__eType_t.getCPtr(vecTypes), Vector_Int.getCPtr(vecCounts)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isValueTileCompatible(PYXTableDefinition_CSPtr spDefn) {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_isValueTileCompatible(swigCPtr, PYXTableDefinition_CSPtr.getCPtr(spDefn));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getTypeCompatibleValue(int nChannelIndex) {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXValueTile_SPtr_getTypeCompatibleValue(swigCPtr, nChannelIndex), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void serialize(SWIGTYPE_p_std__ostream arg0) {
    pyxlibPINVOKE.PYXValueTile_SPtr_serialize(swigCPtr, SWIGTYPE_p_std__ostream.getCPtr(arg0));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void deserialize(SWIGTYPE_p_std__istream arg0) {
    pyxlibPINVOKE.PYXValueTile_SPtr_deserialize(swigCPtr, SWIGTYPE_p_std__istream.getCPtr(arg0));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getHeapBytes() {
    int ret = pyxlibPINVOKE.PYXValueTile_SPtr_getHeapBytes(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public SWIGTYPE_p_CacheStatus getCacheStatus() {
    IntPtr cPtr = pyxlibPINVOKE.PYXValueTile_SPtr_getCacheStatus(swigCPtr);
    SWIGTYPE_p_CacheStatus ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_CacheStatus(cPtr, false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getNumberOfDataChannels() {
    int ret = pyxlibPINVOKE.PYXValueTile_SPtr_getNumberOfDataChannels(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getNumberOfCells() {
    int ret = pyxlibPINVOKE.PYXValueTile_SPtr_getNumberOfCells(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue.eType getDataChannelType(int nChannelIndex) {
    PYXValue.eType ret = (PYXValue.eType)pyxlibPINVOKE.PYXValueTile_SPtr_getDataChannelType(swigCPtr, nChannelIndex);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int getDataChannelCount(int nChannelIndex) {
    int ret = pyxlibPINVOKE.PYXValueTile_SPtr_getDataChannelCount(swigCPtr, nChannelIndex);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getValue(PYXIcosIndex cellIndex, int nChannelIndex, SWIGTYPE_p_bool pbInitialized) {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXValueTile_SPtr_getValue__SWIG_0(swigCPtr, PYXIcosIndex.getCPtr(cellIndex), nChannelIndex, SWIGTYPE_p_bool.getCPtr(pbInitialized)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getValue(PYXIcosIndex cellIndex, int nChannelIndex) {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXValueTile_SPtr_getValue__SWIG_1(swigCPtr, PYXIcosIndex.getCPtr(cellIndex), nChannelIndex), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getValue(PYXIcosIndex cellIndex, int nChannelIndex, PYXValue pValue) {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_getValue__SWIG_2(swigCPtr, PYXIcosIndex.getCPtr(cellIndex), nChannelIndex, PYXValue.getCPtr(pValue));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getValue(int nOffset, int nChannelIndex, SWIGTYPE_p_bool pbInitialized) {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXValueTile_SPtr_getValue__SWIG_3(swigCPtr, nOffset, nChannelIndex, SWIGTYPE_p_bool.getCPtr(pbInitialized)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValue getValue(int nOffset, int nChannelIndex) {
    PYXValue ret = new PYXValue(pyxlibPINVOKE.PYXValueTile_SPtr_getValue__SWIG_4(swigCPtr, nOffset, nChannelIndex), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getValue(int nOffset, int nChannelIndex, PYXValue pValue) {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_getValue__SWIG_5(swigCPtr, nOffset, nChannelIndex, PYXValue.getCPtr(pValue));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setValue(PYXIcosIndex cellIndex, int nChannelIndex, PYXValue value) {
    pyxlibPINVOKE.PYXValueTile_SPtr_setValue__SWIG_0(swigCPtr, PYXIcosIndex.getCPtr(cellIndex), nChannelIndex, PYXValue.getCPtr(value));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setValue(int nOffset, int nChannelIndex, PYXValue value) {
    pyxlibPINVOKE.PYXValueTile_SPtr_setValue__SWIG_1(swigCPtr, nOffset, nChannelIndex, PYXValue.getCPtr(value));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isDirty() {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_isDirty(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isComplete() {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_isComplete(swigCPtr);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setIsComplete(bool isComplete) {
    pyxlibPINVOKE.PYXValueTile_SPtr_setIsComplete(swigCPtr, isComplete);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXTile getTile() {
    PYXTile ret = new PYXTile(pyxlibPINVOKE.PYXValueTile_SPtr_getTile(swigCPtr), false);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setTile(PYXTile tile) {
    pyxlibPINVOKE.PYXValueTile_SPtr_setTile(swigCPtr, PYXTile.getCPtr(tile));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  }

  public PYXIterator_SPtr getIterator() {
    PYXIterator_SPtr ret = new PYXIterator_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_getIterator(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr cloneFieldTile(int nFieldIndex) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_cloneFieldTile(swigCPtr, nFieldIndex), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr clone() {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_clone(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr zoomIn(int nFieldIndex) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_zoomIn(swigCPtr, nFieldIndex), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTileStatistics calcStatistics() {
    PYXValueTileStatistics ret = new PYXValueTileStatistics(pyxlibPINVOKE.PYXValueTile_SPtr_calcStatistics(swigCPtr), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isTileFileComplete(string tileFilename) {
    bool ret = pyxlibPINVOKE.PYXValueTile_SPtr_isTileFileComplete(swigCPtr, pyxlibPINVOKE.UnmanagedString.Create(tileFilename));
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr createFromFile(string tileFilename) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_createFromFile(swigCPtr, pyxlibPINVOKE.UnmanagedString.Create(tileFilename)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public PYXValueTile_SPtr createFromBase64String(string base64) {
    PYXValueTile_SPtr ret = new PYXValueTile_SPtr(pyxlibPINVOKE.PYXValueTile_SPtr_createFromBase64String(swigCPtr, pyxlibPINVOKE.UnmanagedString.Create(base64)), true);
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string toBase64String() {
  // Generated from %typemap(csout) string
  string ret = pyxlibPINVOKE.UnmanagedString.Consume(pyxlibPINVOKE.PYXValueTile_SPtr_toBase64String(swigCPtr));
  
    if (pyxlibPINVOKE.SWIGPendingException.Pending) throw pyxlibPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

}
