/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.30
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

public class IDocument_CSPtr : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public IDocument_CSPtr(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(IDocument_CSPtr obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IDocument_CSPtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        applicationPINVOKE.delete_IDocument_CSPtr(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public IDocument_CSPtr() : this(applicationPINVOKE.new_IDocument_CSPtr__SWIG_0(), true) {
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public IDocument_CSPtr(IDocument p, bool add_ref) : this(applicationPINVOKE.new_IDocument_CSPtr__SWIG_1(IDocument.getCPtr(p), add_ref), true) {
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public IDocument_CSPtr(IDocument p) : this(applicationPINVOKE.new_IDocument_CSPtr__SWIG_2(IDocument.getCPtr(p)), true) {
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public IDocument_CSPtr(IDocument_CSPtr rhs) : this(applicationPINVOKE.new_IDocument_CSPtr__SWIG_3(IDocument_CSPtr.getCPtr(rhs)), true) {
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset() {
    applicationPINVOKE.IDocument_CSPtr_reset__SWIG_0(swigCPtr);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public void reset(IDocument rhs) {
    applicationPINVOKE.IDocument_CSPtr_reset__SWIG_1(swigCPtr, IDocument.getCPtr(rhs));
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public IDocument get() {
    IntPtr cPtr = applicationPINVOKE.IDocument_CSPtr_get(swigCPtr);
    IDocument ret = (cPtr == IntPtr.Zero) ? null : new IDocument(cPtr, false);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IDocument __ref__() {
    IDocument ret = new IDocument(applicationPINVOKE.IDocument_CSPtr___ref__(swigCPtr), false);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public IDocument __deref__() {
    IntPtr cPtr = applicationPINVOKE.IDocument_CSPtr___deref__(swigCPtr);
    IDocument ret = (cPtr == IntPtr.Zero) ? null : new IDocument(cPtr, false);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void swap(IDocument_CSPtr rhs) {
    applicationPINVOKE.IDocument_CSPtr_swap(swigCPtr, IDocument_CSPtr.getCPtr(rhs));
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isNull() {
    bool ret = applicationPINVOKE.IDocument_CSPtr_isNull(swigCPtr);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isNotNull() {
    bool ret = applicationPINVOKE.IDocument_CSPtr_isNotNull(swigCPtr);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GUID iid {
    get {
      IntPtr cPtr = applicationPINVOKE.IDocument_CSPtr_iid_get(swigCPtr);
      GUID ret = (cPtr == IntPtr.Zero) ? null : new GUID(cPtr, false);
      if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string getCameraCookieString() {
  // Generated from %typemap(csout) string
  string ret = applicationPINVOKE.UnmanagedString.Consume(applicationPINVOKE.IDocument_CSPtr_getCameraCookieString(swigCPtr));
  
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
  return ret;
}

  public bool isOutOfDate() {
    bool ret = applicationPINVOKE.IDocument_CSPtr_isOutOfDate(swigCPtr);
    if (applicationPINVOKE.SWIGPendingException.Pending) throw applicationPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
